# Generated by Django 3.2.21 on 2024-01-17 08:31

from django.db import migrations


def load_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(fullname=flat.owner, owners_phonenumber = flat.owners_phonenumber,
                                    owner_pure_phone = flat.owner_pure_phone)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20240117_1126'),
    ]

    operations = [migrations.RunPython(load_owners),
    ]
