# Generated by Django 3.2.21 on 2024-01-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20240117_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текст жалобы'),
        ),
    ]
